name: SoldierGame
main: ifteam\SoldierGame\SoldierGame
version: 1.0-alpha
author: ifteam
api:
- 1.4.1
- 1.12.0
- 1.13.0
- 2.0.0
load: STARTUP

commands:
 soldiergame:
   permission: soldiergame
   description: SoldierGame control commands
   usage: /soldiergame

permissions:
 soldiergame:
  default: op
  description: Allows commands of SoldierGame